### ISSUE TITLE
IOS Bitcode -Enabled SDk

### ISSUE THREAD

**Issue by byzyn4ik** [MobileAppTracking/sdk-release#11]
Where i can get iOS 9 SDK With BitCode enabled , Mixpanel and Flurry already did this , please compile it , yours library is only one dependency that have not supports BITCODE .

**Comment by harshal-hasoffers** [comment]
The updated SDK with "bitcode" support should be available in the next 1-2 days.

**Comment by harshal-hasoffers** [comment]
MAT SDK v3.12.0 with bitcode enabled available for download through Tune dashboard and Cocoapods.
