### ISSUE TITLE
harshal-hasoffers commented 3 days ago that a Bitcode version would be available

### ISSUE THREAD

**Issue by jordanbigel** [MobileAppTracking/sdk-release#12]
I'm forced to either remove MAT from my app, and submit my next version to AppStore, or wait an unknown period of time for a new version of the MAT library. 

harshal-hasoffers commented 3 days ago and said a BITCODE version would be available in 1-2 days. 

You're KILLING ME HERE.

**Comment by hasjohnb** [comment]
It was released yesterday. It may not be available in this repo before
Monday, but you can download SDK v3.12 from the MAT platform website.
