### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by naluhh** [MobileAppTracking/sdk-release#14]
I can't compile because the framework does not support bitcode. Did I do something wrong? 

TuneEvent.o)' was built without full bitcode

V3.14

**Comment by harshal-hasoffers** [comment]
As you can see here https://github.com/MobileAppTracking/sdk-release/blob/master/sdk-ios/Tune/MobileAppTracker.xcodeproj/project.pbxproj#L1504
the MAT SDK is already built with bitcode enabled.

How did you download the framework? using Cocoapods or from the TUNE dashboard?
Do you have a sample app that we can try to repro the issue or a more detailed stack trace?

**Comment by naluhh** [comment]
I did use Cocoapods, but I also tried to add manually the framework with the same result. I downgraded to 3.12 and it works. I think it would be easy to make a sample app, create an app with apple watch support and use the measureEvent func.

**Comment by harshal-hasoffers** [comment]
We have fixed the issue by adding `-fembed-bitcode` to "Other C Flags" in the framework project. The next SDK release v3.14.1 will include this fix and should work fine with apps with bitcode enabled. Thanks for reporting the issue.
