### ISSUE TITLE
Upgrade Android Support Libraries to v24 

### ISSUE THREAD

**Issue by evinugur** [MobileAppTracking/sdk-release#19]
Now that [apps with API 24 can be shipped](http://android-developers.blogspot.com/2016/06/android-n-apis-are-now-final.html), the libraries included with Tune should be updated accordingly.

**Comment by john-gu** [comment]
Hi, this is fixed in 4.4.0:
https://github.com/MobileAppTracking/sdk-release/releases/tag/android-4.4.0

Thanks!
