### ISSUE TITLE
SDK 4.3.0 : Fatal Exception: java.lang.SecurityException

### ISSUE THREAD

**Issue by jt-gilkeson** [MobileAppTracking/sdk-release#20]
Fatal Exception: java.lang.SecurityException: app from uid XXX not allowed to perform FINE_LOCATION
at com.tune.location.TuneLocationListener$GetLocationUpdates.run(TuneLocationListener.java:207)

com.tune:tune-marketing-console-sdk:4.3.0

Device is  ONE E1003  5.1.1 (Lollipop) 

May be a device-specific issue since we only see one instance of this crash.
Looks like Google ran into this too:

https://bugs.chromium.org/p/chromium/issues/detail?id=580733

**Comment by john-gu** [comment]
Hi @jt-gilkeson, thanks for reporting this. We'll get a fix for this out in our next release.

**Comment by john-gu** [comment]
A fix for this has been released in 4.5.1:
https://github.com/MobileAppTracking/sdk-release/releases/tag/android-4.5.1

Thanks!
