### ISSUE TITLE
iOS: Some function documentation have wrong parameter names

### ISSUE THREAD

**Issue by Myrronth** [MobileAppTracking/sdk-release#23]
I have Tune 4.8.0 added to my project via CocoaPod 1.0.1. My project treats warnings as errors and has the clang flag `-Wdocumentation` enabled. Building my app results in 5 errors in 2 files:

- TuneDebugUtilities.h#16 `* param enable`should be `* param enableDebug`
- Tune.h#409 `* param variableName`should be `* param name`
- Tune.h#419 `* param variableName`should be `* param name`
- Tune.h#429 `* param variableName`should be `* param name`
- Tune.h#439 `* param variableName`should be `* param name`

Adding `-Wno-documentation` to the build config in CocoaPods post_install hook does not fix the problem. I think this is due to the fact that Tune gets installed as a framework?

Are there any workarounds until the source is fixed?

**Comment by harshal-hasoffers** [comment]
Thanks for pointing this out, we will include the var name fixes in today's release.

**Comment by harshal-hasoffers** [comment]
v4.9.0 is now released.
