### ISSUE TITLE
WP8 dll can't be imported

### ISSUE THREAD

**Issue by riccardo91** [MobileAppTracking/sdk-release#3]
Hello Team,
You should set "All Platforms" in Project settings ->Build->Platform

**Comment by john-gu** [comment]
Hi @riccardo91, what's the import error you're seeing?

We are currently building for Any CPU, is that different from All Platforms? When I select All Platforms the output still says it's building for Any CPU.

**Comment by riccardo91** [comment]
Hello @john-gu, if you reference the dll to a new project an error will be raised. Instead if you reference the Project everythings works well

**Comment by john-gu** [comment]
I was not able to repro this unless you are referring to this:
http://stackoverflow.com/questions/13698094/referencing-zxing-net-library/13698737#13698737

We have added the "Unblock" step to our Windows Quick Start guide.

Thanks!
