### ISSUE TITLE
Please provide android sdk at central or jcenter

### ISSUE THREAD

**Issue by cemo** [MobileAppTracking/sdk-release#5]
Please upload mobile app tracker jar file to a common place such as central and jcenter.

**Comment by john-gu** [comment]
Hi cemo, we currently have plans to do this - please stay tuned!

**Comment by john-gu** [comment]
Hi @cemo, we've made our 4.0.0+ SDK available in jcenter:
https://bintray.com/tune/TuneMarketingConsoleSDK/TuneMarketingConsoleSDK/v4.0.1/view

New implementation steps can be found here:
https://developers.mobileapptracking.com/android-sdk/

Update steps:
https://developers.mobileapptracking.com/migrating-sdk-from-3-x-x-to-4-x-x/

Thanks!
