### ISSUE TITLE
setShouldAutoCollectDeviceLocation not working

### ISSUE THREAD

**Issue by naluhh** [MobileAppTracking/sdk-release#7]
Even If I set setShouldAutoCollectDeviceLocation to false, tune still track the user position, which is unacceptable!
Minimal code to reproduce:

    func applicationDidBecomeActive(application: UIApplication) {
        Tune.setShouldAutoCollectDeviceLocation(false)
        Tune.measureSession()
    }

**Comment by harshal-hasoffers** [comment]
Thanks for contacting us. We are probing this further, will update you soon.

**Comment by harshal-hasoffers** [comment]
Issue fixed in latest version of MAT iOS SDK 3.11.1.
