### ISSUE TITLE
duplicate symbol l070

### ISSUE THREAD

**Issue by kkunowski** [MobileAppTracking/sdk-release#8]
duplicate symbol l070 in:
... /MobileAppTracker.framework/MobileAppTracker(TuneDeferredDplinkr.o)
... /MobileAppTracker/MobileAppTracker.framework/MobileAppTracker(TuneEventQueue.o)
1 duplicate symbol for architecture arm64

This issue still appears in:
MobileAppTracker 3.11.0
Yosemite 10.10.5 (14F27)
Xcode 6.2 (6C131e)
iOS SDK 8.2
Swift iOS project
when building for arm64 (i.e. preparing archive for itunes)
On Simulator build OK.
Any idea how to fix it ?

**Comment by kkunowski** [comment]
It compiles under Swift 1.2 (in xCode > 6.3) .. any option to support Swift 1.0 ?

**Comment by harshal-hasoffers** [comment]
Can you test with the latest Xcode 7.0?

**Comment by harshal-hasoffers** [comment]
closing inactive ticket
